#!/usr/bin/env bash
# Generate nango/.env with real secrets. Idempotent: refuses to clobber an
# existing .env (the encryption key must never change once data is encrypted).
set -euo pipefail
cd "$(dirname "$0")"

if [[ -f .env ]]; then
  echo ".env already exists — leaving it untouched (encryption key must be stable)."
  echo "Delete it manually only if you also wipe ./nango-data (loses all credentials)."
  exit 0
fi

gen() { openssl rand -base64 "${1:-24}" | tr -d '\n'; }

ENC_KEY="$(gen 32)"          # 256-bit, base64
DB_PASS="$(gen 24 | tr '/+=' 'xyz')"   # keep it URL-safe for RECORDS_DATABASE_URL
DASH_PASS="$(gen 18 | tr '/+=' 'xyz')"

cat > .env <<EOF
# Generated by setup.sh — DO NOT commit. NANGO_ENCRYPTION_KEY is permanent.
NANGO_ENCRYPTION_KEY=${ENC_KEY}

NANGO_DB_USER=nango
NANGO_DB_PASSWORD=${DB_PASS}
NANGO_DB_NAME=nango
NANGO_DB_HOST=nango-db
NANGO_DB_PORT=5433

SERVER_PORT=3003
CONNECT_UI_PORT=3009
NANGO_SERVER_URL=http://localhost:3003
NANGO_PUBLIC_SERVER_URL=http://localhost:3003
NANGO_PUBLIC_CONNECT_URL=http://localhost:3009

NANGO_DASHBOARD_USERNAME=admin
NANGO_DASHBOARD_PASSWORD=${DASH_PASS}

LOG_LEVEL=info
EOF
chmod 600 .env
echo "Wrote nango/.env (chmod 600)."
echo "Dashboard login:  admin / ${DASH_PASS}"
